Entities/Bus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TransportManagementSystem.Enums;

namespace TransportManagementSystem.Entities
{
    public class Bus : BaseEntity
    {
        public string Model { get; set; }

        public BusType BusType { get; set; }

        public string RegistrationNumber { get; set; }

        public string PlateNumber { get; set; }

        public int Capacity { get; set; }

        public bool AvailabilityStatus { get; set; }

        public bool TripStatus { get; set; }

        public ICollection<Trip> Trips { get; set; } = new List<Trip>();
    }
}

Controllers/BusController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TransportManagementSystem.Interfaces.Services;
using TransportManagementSystem.Models;

namespace TransportManagementSystem.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusService _busService;

        public BusController(IBusService busService)
        {
            _busService = busService;
        }
        public IActionResult Index()
        {
            return View(_busService.GetBuses());
        }

        public IActionResult RegisterBus()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterBus(CreateBusRequestModel busModel)
        {
            _busService.RegisterBus(busModel);
            return RedirectToAction("Index");
        }

    }
}

Controllers/TripController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TransportManagementSystem.Enums;
using TransportManagementSystem.Interfaces.Services;
using TransportManagementSystem.Models;

namespace TransportManagementSystem.Controllers
{
    public class TripController : Controller
    {
        private readonly ITripService _tripService;
        private readonly IUserService _userService;
        private readonly IBookingService _bookingService;
        public TripController(ITripService tripService, IUserService userService, IBookingService bookingService)
        {
            _tripService = tripService;
            _userService = userService;
            _bookingService = bookingService;
        }
        public IActionResult Index()
        {
            return View(_tripService.GetTrips());
        }

        public IActionResult SearchTrip(Location from, Location to, DateTime date)
        {
            return View(_tripService.GetScheduledTripsByLocationByDate(from, to, date));
        }
        public IActionResult ScheduleTrip(int id)
        {
            var drivers = _userService.GetDrivers();
            ViewData["Drivers"] = new SelectList(drivers, "Id", "FirstName");
            return View();
        }

        [HttpPost]
        public IActionResult ScheduleTrip(CreateTripRequestModel model)
        {
            _tripService.ScheduleTrip(model);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult BookTicket(int id)
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult BookTicket(CreateBookingRequestModel model)
        {

           var bookingReference = _bookingService.BookTicket(model);
            return RedirectToAction("SuccessPage", new { bookingReference.BookingReference });
        }


        public IActionResult SuccessPage(string bookingReference)
        {
            var booking = _bookingService.GetByReference(bookingReference);
            if (booking == null)
            {
                return NotFound();
            }
            else
            {
                return View(booking);
            }
        
        }
    }
}

Views/Bus/Index.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Admin";
}
@model IEnumerable<TransportManagementSystem.Models.BusDTO>




<div class="card-header" style="background-color:aliceblue;">
    <div class="card-title">
        <h1 class="text-center">Buses</h1>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.AvailabilityStatus)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TripStatus)
            </th>


            <th>
                Schedule Trip
            </th>

            <th>
                Update
            </th>
            <th>
                Details
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => student.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.BusType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.AvailabilityStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => student.TripStatus)
            </td>
            <td>
                <a asp-action="ScheduleTrip" asp-controller="Trip"   asp-route-id="@student.Id">Schedule </a>
            </td>
            <td>
                <a asp-action="Update" asp-route-id="@student.Id">Update</a>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@student.Id">Details</a>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@student.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<button style="background-color:wheat;"><a asp-controller="Bus" asp-action="RegisterBus">Register Bus</a> </button>

Views/Bus/RegisterBus.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Admin";
}
@using TransportManagementSystem.Enums
<div class="breadcrumb-area breadcrumb-area-padding-2 bg-gray-2">
    <div class="custom-container">
        <div class="breadcrumb-content text-center">
            <ul>
                <li>
                    <a asp-controller="home" asp-action="index">Home</a>
                </li>
                <li class="active">register </li>
            </ul>
        </div>
    </div>
</div>
<div class="login-register-area pt-75 pb-75">
    <div class="container">
        <div class="login-register-wrap">
            <div class="login-register-title text-center">
                <h1>Register Bus</h1>
            </div>
            <div class="login-register-form">
                <form asp-action="RegisterBus">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">

                            <div class="login-register-input-style input-style">
                                <label>Model*</label>
                                <input type="text" name="Model" required>
                            </div>
                            <div class="login-register-input-style input-style">

                                <label class="control-label">Bus Type</label>
                                <select name="BusType" class="form-control">
                                    Select Bus Type
                                    <option value="@BusType.BusinessClass"> Business Class</option>
                                    <option value="@BusType.Economy"> Economy</option>
                                    <option value="@BusType.FirstClass"> First Class</option>
                                </select>
                                

                            </div>
                            <div class="login-register-input-style input-style">
                                <label>Registration Number*</label>
                                <input type="text" name="RegistrationNumber" required>
                            </div>



                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="login-register-input-style input-style">
                                <label>Plate Number *</label>
                                <input type="text" name="PlateNumber" required>
                            </div>
                            <div class="login-register-input-style input-style">
                                <label>Capacity *</label>
                                <input type="number" name="Capacity" required>
                            </div>

                            <div class="login-register-btn">
                                <button type="submit">Register</button>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>